[package]
name = "revmc-sim-load"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[dependencies]
revmc.workspace = true
revm.workspace = true
eyre.workspace = true
libloading.workspace = true
tracing = "0.1.40"
